# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  component-tests:
    docker:
      - image: cimg/base:current
      - image: solace/solace-pubsub-standard:10.1.0.19
        environment: 
          username_admin_globalaccesslevel: $ENV_GLOBALACCESSLEVEL
          username_admin_password: $ENV_GLOBALACCESSLEVEL
        user: "12121"   #needed or else image won't startup
    working_directory: /tmp
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Sleep - to wait for container to really start"
          command: "sleep 60"
      - run:
          name: "Show ports"
          command: "netstat -tulpn"
      - run:
          name: "SEMP no password"
          command: "curl -XGET http://localhost:8080/SEMP/v2/config/spec"
      - run:
          name: "SEMP using mgmt user set via env"
          command: "curl -XGET http://localhost:8080/SEMP/v2/config/msgVpns -u $ENV_GLOBALACCESSLEVEL:$ENV_GLOBALACCESSLEVEL"
        

workflows:
  test-solace:
    jobs:
      - component-tests
