# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# I don't think we need an orb?
orbs: 
  docker: circleci/docker@2.1.2

jobs:
  component-tests:
    docker:
      - image: solace/solace-pubsub-standard:10.1.0.19
        # does there need to be a working directory for the image?
        # working_directory: ~/workspace
        environment: 
          username_admin_globalaccesslevel: $ENV_GLOBALACCESSLEVEL
          username_admin_password: $ENV_USER_PASSWD
        user: "12121"   #needed or else image won't startup
        working_directory: "/tmp"
    steps:
      - run:
          name: run component tests
          command: |
            exec bash
            make component-tests

workflows:
  test-solace:
    jobs:
      - component-tests
